### PR TITLE
initial fix to cr volume

### LINKED ISSUE #39: Adding new volumes to CRs yields broken StatefulSet
Create a Standalone, IndexerCluster, SearchHeadCluster or LicenseMaster CR. Modify the spec the include additional `volumes`. Operator updates StatefulSet to include the new container VolumeMount, but fails to include the Volume spec in the template.

Operator next will recognize that the pods require updates, shutdown and terminate the highest-numbered pod. The pod will fail to restart because the spec for the container references a Volume that it doesn't recognize. It will remain stuck in this state until you remove the `volumes` from the corresponding CR, at which point it fixes itself.

### PR DESCRIPTION
**Pull request by kelvinatsplunk**
Fixed #39. Added cr.Volumes check and initialize optional properties in cr.Volumes to default values.

### CODE REVIEW

File: pkg/splunk/enterprise/configuration.go [hunk 1]
```diff
@@ -196,6 +196,33 @@ func GetSplunkService(cr enterprisev1.MetaObject, spec enterprisev1.CommonSpec,
 	return service
 }
 
+// validateVolumes initializes optional properties in Volumes to default values
+func validateVolumes(spec *enterprisev1.CommonSplunkSpec) {
```
Comment (gjothikumar-splunk) [inline pkg/splunk/enterprise/configuration.go]: The name "validateVolumes" seems to be misleading as we are setting default values to the spec objects. Something like setDefaults or initDefaults ?

File: pkg/splunk/enterprise/configuration.go [hunk 2]
```diff
@@ -556,20 +583,28 @@ func updateSplunkPodTemplateWithConfig(podTemplateSpec *corev1.PodTemplateSpec,
...
 
+	// Explicitly set the default value here so we can compare for changes correctly with current statefulset.
+	secretVolDefaultMode := int32(corev1.SecretVolumeSourceDefaultMode)
+
 	// add defaults secrets to all splunk containers
 	addSplunkVolumeToTemplate(podTemplateSpec, "secrets", corev1.VolumeSource{
 		Secret: &corev1.SecretVolumeSource{
-			SecretName: GetSplunkSecretsName(cr.GetIdentifier(), instanceType),
+			SecretName:  GetSplunkSecretsName(cr.GetIdentifier(), instanceType),
+			DefaultMode: &secretVolDefaultMode,
```
Comment (gjothikumar-splunk) [inline pkg/splunk/enterprise/configuration.go]: Since the default mode is already set above (validateVolumes) can't it be retrieved from the CR spec here instead of initializing with corev1.SecretVolumeSourceDefaultMode.

File: pkg/splunk/enterprise/configuration.go [hunk 3]
```diff
@@ -556,20 +583,28 @@ func updateSplunkPodTemplateWithConfig(podTemplateSpec *corev1.PodTemplateSpec,
...
+	configMapVolDefaultMode := int32(corev1.ConfigMapVolumeSourceDefaultMode)
+
 	// add inline defaults to all splunk containers
 	if spec.Defaults != "" {
 		addSplunkVolumeToTemplate(podTemplateSpec, "defaults", corev1.VolumeSource{
 			ConfigMap: &corev1.ConfigMapVolumeSource{
 				LocalObjectReference: corev1.LocalObjectReference{
 					Name: GetSplunkDefaultsName(cr.GetIdentifier(), instanceType),
 				},
+				DefaultMode: &configMapVolDefaultMode,
```
Comment (gjothikumar-splunk) [inline pkg/splunk/enterprise/configuration.go]: Since the default mode is already set above (validateVolumes) can't it be retrieved from the CR spec here instead of initializing with corev1.ConfigMapVolumeSourceDefaultMode.

**Comment by gjothikumar-splunk** [comment]
Just confirming, since this is a bug on existing 0.1.0 release this will be merged to master and develop. Is that correct

File: pkg/splunk/enterprise/configuration.go (hunk 1 above)
Comment (kelvinatsplunk) [reply pkg/splunk/enterprise/configuration.go]: I will change it to setVolumeDefaults()

File: pkg/splunk/enterprise/configuration.go (hunk 2 above)
Comment (kelvinatsplunk) [reply pkg/splunk/enterprise/configuration.go]: validateVolumes() validates/set what the user specified in the CR. The addSplunkVolumeToTemplate() adds **additional** volumes after what the user adds in the CR.

File: pkg/splunk/enterprise/configuration.go (hunk 3 above)
Comment (kelvinatsplunk) [reply pkg/splunk/enterprise/configuration.go]: Comment above
